### ISSUE TITLE
Request: option to add extra spaces to end of song name

### ISSUE THREAD

**Issue by kyds3k** [nockscitney/SeratoNowPlaying#10]
I'm using this to show my currently playing track on Streamlabs OBS (on Mac). My issue is - when I loop it, the track name repeats with no space in between, which is a little confusing. Is there any way to add an option to add some padding to the end of the name? Other than that - I'm LOVING this, just getting into streaming and this is awesome!

**Comment by bushmstr02** [comment]
@kyds3k you wouldn't happen to have the original zip file for serato now playing lite you could email me would you ? the zip file on here isn't right and he has to fix it next week but was trying to get something going soon

**Comment by nockscitney** [comment]
> @kyds3k you wouldn't happen to have the original zip file for serato now playing lite you could email me would you ? the zip file on here isn't right and he has to fix it next week but was trying to get something going soon

You can find the pre-release version in the releases page if you wanted to try that. https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snpl-pr-0.9

**Comment by nockscitney** [comment]
@kyds3k thanks for raising the issue. I’m this is already something that’s been raised in Issue #8 and I’m hoping to have this on there in the next release, next week

**Comment by nockscitney** [comment]
The issue is now resolved.  Leading and trailing spaces have been added to track label write method - The latest releases are:

- Serato Now Playing: https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snp-1.1.1.0
- Serato Now Playing Lite: https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snpl-1.0.1.0
