### ISSUE TITLE
Doesn't Refresh Songs

### ISSUE THREAD

**Issue by marcweezy** [nockscitney/SeratoNowPlaying#12]
Tried several times. It will read the first current song but will not refresh for the next songs. Using Pioneer DDJ1000srt

**Comment by nockscitney** [comment]
When it stops refreshing the song names, can you confirm whether or not the Serato Live playlist is being update on the website or not?

**Comment by marcweezy** [comment]
Fixed. It was the refresh time. It defaults at 900 seconds, not milliseconds.
