### ISSUE TITLE
Cnnot fine SeratoNowPlaying-Lite for mac

### ISSUE THREAD

**Issue by MarVesEDM** [nockscitney/SeratoNowPlaying#13]
can't seem to find the mac version for SeratoNowPlaying-Lite

**Comment by nockscitney** [comment]
The latest release for the Lite version is here - https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snpl-1.0.1.0

**Comment by djronniebruno** [comment]
I dont see the mac version either. When I open the lite version I see a macos folder inside the runtimes folder that have dll files.
