### ISSUE TITLE
Prevent constantly writing to the file

### ISSUE THREAD

**Issue by aerond7** [nockscitney/SeratoNowPlaying#3]
By checking task manager I noticed that the app is constantly writing to disk (to the file)

An easy solution to prevent this is as follows; you could save the track name in a variable and check it against what the app is getting from the web. If what we got from the web is different to the string saved in memory then only in that case write to the file and save the new song name to the variable and continue checking.

**Comment by nockscitney** [comment]
Thanks @aerond7 - It’s now on the improvements list 🙂

**Comment by nockscitney** [comment]
Implemented and resolved in Version 1.1.0
