### ISSUE TITLE
Allow the user to add a prefix or suffix to the output

### ISSUE THREAD

**Issue by Lil-Jening** [nockscitney/SeratoNowPlaying#5]
This program works perfectly, I do request that there can be two new text boxes added to the UI, allowing the output to have a custom prefix and suffix added.

**Comment by Lil-Jening** [comment]
I cloned and edited something together that may work. But its been a while since i used C#, so its probably really poorly done. You can use that as reference.

**Comment by nockscitney** [comment]
Issue resolved in Version 1.1.0 Release
