### ISSUE TITLE
Request: Enabled For MacOS

### ISSUE THREAD

**Issue by heytorio** [nockscitney/SeratoNowPlaying#6]
With most DJs using Serato DJ Pro on a Macbook, is there a way to create this program for mac users? I have tried to run the setup.exe file using a 3rd party application named Wine but the program did not work. I can provide the error message if necessary.

**Comment by nockscitney** [comment]
Hey @heytorio - I don’t know much about Mac development at all (always developed for windows platform). I can look into it, however I may be able to come up with a web interface with the same / similar functionality. Let me have a think over it.

**Comment by heytorio** [comment]
Thanks @nockscitney ! I tried to create a work around by creating a RSS feed that pulls from the Serato Live playlist but I couldnt get the feed to update in real-time. Would be awesome if the web interface could pull the "now playing" track and we could integrate that text into our streams!

**Comment by XaMMiD** [comment]
Thanks for looking into this! 

I'm desperately looking for a tool like this on Mac. A web-interface is fine too, any way to get exactly this done on a Mac is great. At this point I cannot find any other way on how to export/save the NowPlaying info from Serato into a txt file ...

I was so happy to find this page, only to find out it's for Windows only :-)

I hope you find the time and will to help Mac users ;-)

Thanks in advance for your effort!

**Comment by nockscitney** [comment]
> Thanks @nockscitney for looking into this!
> 
> I'm desperately looking for a tool like this on Mac. A web-interface is fine too, any way to get exactly this done on a Mac is great. At this point I cannot find any other way on how to export/save the NowPlaying info from Serato into a txt file ...
> 
> I was so happy to find this page, only to find out it's for Windows only :-)
> 
> I hope you find the time and will to help Mac users ;-)
> 
> Thanks in advance for your effort!

I have an idea about porting this over to .NET CORE, which is the open source framework version of .net, compatible with Macs.  I just need to find some time.

Watch this space :)

**Comment by krrish15** [comment]
Hey, is there any update on the mac version?

**Comment by nockscitney** [comment]
> Hey, is there any update on the mac version?

I’ve been looking into it and I think there may be a “Quick Fix” to get Mac users up and running. However there’s two things to note with this: 

1) I don’t currently have a Mac, so while I can develop something with .net Core to run on a Mac, I can’t 100% say how to use it / if it will work
2) the .net core library for mac doesn’t seem to have a GUI. Therefore the app may have to be a console app, which isn’t ideal as it would mean that it would need configuring in a text file as opposed to having a nice set of text boxes to do it. However, if it’s a short term fix, then it’s an option. 

I’m hoping to find some more time this week to look at it in more detail as it’s becoming more apparent that It’s a highly desired feature

**Comment by krrish15** [comment]
Thanks for the response looking forward to it!

**Comment by renderf0x** [comment]
@nockscitney If that doesn't pan out, I can take a look at doing a native Mac port. Seems like it should be reasonably simple to port the logic over. LMK.

**Comment by nockscitney** [comment]
Following successful testing, I have just released the first full Version of Searto Now Playing - Lite which can be found at the following release page - https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snpl1.0.0.0

This issue will now be closed so any further issues relating to this can be created as new on-going issues.

Thanks again for your patience with this :)
