### ISSUE TITLE
confused on zip file after unzipping 

### ISSUE THREAD

**Issue by bushmstr02** [nockscitney/SeratoNowPlaying#9]
ive done everything up until the terminal to make sure botnet was installed . I download the very first zip folder named SeratoNowPlaying-lite.v.1.0.0.0.zip . When I unzip it creates a folder named " publish " ( I even tried to change the name to the zip folders name with not luck ) . I'm confused on how to go any further and when I open terminal and type in the commands /Users/myUSERNAME/Downloads/SeratoNowPlaying-Lite v1.0.0.0/ says no such file exist and when I type
/Users/myUSERNAME/Downloads/publish/ it says access denied . If I go to file info and change it to let me take control of folder and apply to enclosed folders and try again with " publish or SNPlaying " it says file doesn't exist . I don't where to go from here because this is all foreign language to me and I do not know a whole lot about Macs systems , please help I really need a detailed description on how to do this because I really need this asap on the Mac .

**Comment by nockscitney** [comment]
Thanks for raising the issue. 

If there is a publish folder then I must have zipped the folder up incorrectly when I created the release, in which case I apologise and as soon as I’m back at my pc (currently on vacation) I’ll try to get a new release sorted with the correct folder structure. 

The issue for me is that I don’t own a Mac myself and don't know a lot about them. When I created this release / lite version I had to borrow a friends Mac to do testing and the instructions I provided on the release / read me pages are what I did myself. Outside of that You probably know more about how Macs work that I do. 

I would say let me get an update sorted next week, try again with that and then we can go from there to try and resolve any further issues. Sorry that you’ll have to wait, but like I said I’m currently on vacation.

**Comment by bushmstr02** [comment]
Thank you for the quick response , enjoy your vacation and look forward to fixing this next week !

**Comment by nockscitney** [comment]
@bushmstr02 

The latest version of SNP Lite has the corrected folder structure, so it will follow as per the instructions.  The latest release can be found here:

Serato Now Playing Lite: https://github.com/nockscitney/SeratoNowPlaying/releases/tag/snpl-1.0.1.0

Did you have any joy going to the pre-release version?

**Comment by bushmstr02** [comment]
I can't get it to do anything but im not used to using terminal 
***cd"/users/brianjordan/seratonowplaying-lite v1.0.0.0/"    no matches found 
/users/brianjordan/downloads/seratonowplaying-lite.v1.0.0.0/     no such file or directory 

tried the older version
/users/brianjordan/downloads/seratonowplaying-lite/     permission denied ( im the administrator and have the permissions for read and write ) no clue if im doing anything wrong or if it has something to do with Catalina 10.15.6 , was going to try and use Wine like the other guy off YouTube but wine won't run with the new version of Catalina of course

**Comment by bushmstr02** [comment]
sorry that was sup to be  ***cd"/users/brianjordan/downloads/seratonowplaying-lite v1.0.0.0/"  ... no matches found

**Comment by nockscitney** [comment]
@bushmstr02 I’m so sorry, the instructions are wrong. I feel so stupid. I tried to add format bug and it’s seems to be misleading. 

The cd command shouldn’t have any ***. It should simply be 

cd "/users/brianjordan/downloads/seratonowplaying-lite v1.0.0.0/"

(Making sure there’s a space between cd and the file path). 

Let me know how that goes and I’m so sorry again 🙁

**Comment by nockscitney** [comment]
@bushmstr02 Also, if you’ve downloaded the new version, make sure you target the right path. The update path will be "/users/brianjordan/downloads/seratonowplaying-lite v1.0.1.0/"

**Comment by bushmstr02** [comment]
Nah its all good , I know you aren't a Mac guy and don't have one to work with and just glad you're trying to help .
cd "/users/brianjordan/downloads/seratonowplaying-lite v1.0.1.0/“   it comes up [dquote>

**Comment by nockscitney** [comment]
Have you tried to break it down.  CD basically stands for "Change Directory" so you can try doing one folder at a time, in the right order.  Try each of the following in this order, one by one:

- cd /users/
- cd /brianjordan/
- cd /downloads/
- cd /SeratoNowPlaying-Lite.v1.0.1.0/

**Comment by bushmstr02** [comment]
ok I was about ready to give up but something told me to right click on the unzipped folder and see what actions were available . The last thing was " new terminal at folder " and it opened with the folders name at the top and  brianjordan@Brians-iMac-Pro SeratoNowPlaying-Lite.v1.0.1.0 % in the box . Typed     dotnet SeratoNowPlaying-Lite.dll and it actually opened this time . 

I left the parse time the same and set the track file to current track.txt    
says its running so how is it used ? 

its not asking me for my url for serato

**Comment by bushmstr02** [comment]
ok its working as far as recording the current track in current track folder , now to get obs reading it

**Comment by bushmstr02** [comment]
Thank you so much for working with me its working and I only have one question . Is that in actual seconds it pulls the new track ? One of the videos you recommended said it was actually seconds even though it says it was on the windows version he was using .

**Comment by nockscitney** [comment]
> Thank you so much for working with me its working and I only have one question . Is that in actual seconds it pulls the new track ? One of the videos you recommended said it was actually seconds even though it says it was on the windows version he was using .

Awesome, so glad you got it working 🙂. Sorry for the delay in the reply I’ve been streaming myself tonight. 

The time is in seconds. I tend to have mine set to 60 seconds. There’s no ideal timing that can be set with this as it’s really down to when the program polls for the update in relation to the transition. It’s just playing around and seeing what works best for you. 

I have an idea in the pipeline to make it more streamlined and predictable, so that will come in a later version. 

If there’s any other issues please do let me know and I’ll be happy to help where I can.

**Comment by bushmstr02** [comment]
awesome and I will
